# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Greg's Soapbox
email: greg@gregbee.ch
description: >
  Mostly me whining about how you're building software wrong.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gregbeech.github.io" # the base hostname & protocol for your site
twitter_username: gregbeech
github_username:  gregbeech

# Build settings
markdown: kramdown
